### ISSUE TITLE
Multitouch problem

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#13]
We have a fairly general problem with just touching multiple hexes at once where lights will turn on and stay on when they're not supposed to.

Found it while trying to resolve #12, they're likely related but  I figured I'd post this in case they aren't and I forget to later

**Comment by mulshine** [comment]
noticed this too! when we press lots of keys really fast some will stick.
could be because we r resetting the top keyboard hexes every time a key is
pressed and the communication from mate to manta is just overloaded
(dropping some data). should find a way to not have to reset leds for
keyboard every press. should be simple

**Comment by spiricom** [comment]
I haven't noticed this before, so it may have been introduced by some of the new code from 10/28.

**Comment by mulshine** [comment]
I think this is an imagined issue - instead, a limitation of the hardware. The small spaces between the conductive material within each hex can have the adverse effect of separating user input events. Imagine sliding

**Comment by mulshine** [comment]
currentHexUI and prevHexUI were being updated before their UI states changed.
