### ISSUE TITLE
uhi_hid_manta - func_button_states are just being set to zero?

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#17]
In order to resolve #16, I was trying to access the`func_button_states` and figure out what I needed to check to ensure we only changed the LED while we were in the red state of the top left function button. However, it seems they're never set to anything? The code is a bit obfuscated: 

```
for(i=0; i<4; i++)
{
    func_button_states[i] = uhi_hid_manta_dev.report[i+49] + 0x80;
}
```

@spiricom Perhaps you know what is up with this code or know where we should look?

Thanks!

**Comment by spiricom** [comment]
Hi Josh, 
I think the issue is that you're expecting that array to hold the states of the settings that the manta mate is creating from those function button presses, i.e. toggling on and off different modes, but really that array is to expose the data that is coming from the Manta directly. That means that func_button_states[] represents the current state of those buttons, which are always momentary, only showing positive values when a finger is touching them. 

If you wanted the data about which state the MantaMate thinks the slider representation is in, you need to check the cvouts_vs_steplength variable, which will show a 0, 1, or 2 depending on which bank is selected. The LED data for that top right function button that is sent to the Manta is intended to reflect the state of that variable. 

If you want to understand the line you quote - uhi_hid_manta_dev.report[] is the USB report from the Manta that includes all the data about the current state of all buttons, hexagons, and sliders. Each element of this array is 8 bits. Index numbers 49, 50, 51, and 52 are the function button reports, and they are sent as a signed integer, even though they are unsigned (to avoid a bug in how Windows and Mac handle USB reports differently when designing the original Manta firmware). Therefore, I add 0x80 to each 8 bit number to treat it as unsigned, so that -128 to 127 becomes 0 to 255. Now you have an array of four numbers that are the current capacitance reading of those function buttons only. 

-Jeff

**Comment by mulshine** [comment]
Assuming this is a non-issue at this point.
