### ISSUE TITLE
Stepping does not start -- ordered touch mode

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#3]
I cannot remember the details of this bug, perhaps @spiricom could provide some details in the comments 😄

**Comment by spiricom** [comment]
Yup - when the mode is set to ORDER instead of PATTERN, it sometimes ignores incoming gates and doesn't step for a long time when first turned on. Then, sometimes it starts stepping at some point, seemingly randomly. I think there just some kind of off by one thing or a variable isn't initialized correctly.
