### ISSUE TITLE
External stepping with Square/Saw oscillators not working

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#58]
@spiricom and I noticed this while testing the new hardware. Good news is it works for Sin,Tri, strange envelope inputs, and normal trigger inputs!

**Comment by spiricom** [comment]
Hmm - have we closed this yet? I think I need to check it on the scope and see why it might be doing that... This is the last hardware bug I need to solve before doing the final hardware run. I've integrated the other hardware fixes already. 
-Jeff

**Comment by mulshine** [comment]
yeah i wasnt sure. ill open it again!

**Comment by spiricom** [comment]
Solved. The issue was that I didn't need to drop the voltage down on the gate input via a voltage divider. In our tests, the square was actually just at a lower amplitude, and therefore wasn't triggering the gate. Removing the voltage divider makes it more sensitive and less likely to have trouble with low-level inputs.
